### ISSUE TITLE
Migrate bundle to package for Laravel 4

### ISSUE THREAD

**Issue by fhferreira** [FakeHeal/opauth-laravel#1]
This is possible ?

**Comment by yf-hk** [comment]
+1 for this

**Comment by fakeheal** [comment]
I'm planning to do it this week. Thanks for your concern.

**Comment by webshark** [comment]
Hi,

Did you happen to get around to migrating for laravel 4?

**Comment by fakeheal** [comment]
Yes,

I will upload the new version this weekend.

**Comment by adonespitogo** [comment]
Hi,

Any update for L4 support?

**Comment by pafnuty** [comment]
+1

**Comment by nbcsteveb** [comment]
+1

**Comment by index-panayotov** [comment]
+1.5

**Comment by fakeheal** [comment]
There's a branch called `laravel-4` now.
